all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
all_joints_names:
- front_left_paw
- front_right_paw
- back_left_paw
- back_right_paw
- nose
- neck
- tail_base
- tail_tip
- centroid
alpha_r: 0.02
apply_prob: 0.5
batch_size: 16
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_foot_faultJun7/foot_fault_Jaden95shuffle2.mat
dataset_type: albumentations
decay_steps: 30000
display_iters: 1000
engine: pytorch
global_scale: 0.8
init_weights: /home/jhs8cue/.conda/envs/deeplabcut-env/lib/python3.10/site-packages/deeplabcut
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_foot_faultJun7/Documentation_data-foot_fault_95shuffle2.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 9
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /sfs/gpfs/tardis/home/jhs8cue/foot_fault-Jaden-2025-06-07
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
